config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "problems#index"
  resources :users, only: [:show] do
    member do
      get 'profile'
      patch 'profile_update'
      get 'profile_edit'
    end
  end

  resources :problems do
    resources :comments, only: :create
    resources :solved_worries, only: :create
    collection do
      get 'search'
    end
    member do
      get 'best_answer'
    end
  end

  
    
  

  post 'user/:user_id/problem/:id', to: 'best_users#best_create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/best_user.rb
class BestUser < ApplicationRecord
  belongs_to :user
  belongs_to :problem
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :problem

  
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1, name: '非公開' },
    { id: 2, name: '男性'   },
    { id: 3, name: '女性'   }
  ]
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '健康'},
    { id: 3, name: '仕事・職場'},
    { id: 4, name: '人間関係'},
    { id: 5, name: '恋愛・夫婦'},
    { id: 6, name: '経済・資産'},
    { id: 7, name: '子育て・結婚'},
    { id: 8, name: 'その他'}
  ]
end

app/models/problem.rb
class Problem < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :genre
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image
  has_one :solved_worrie, dependent: :destroy
  has_one :best_user, dependent: :destroy

  def self.search(search)
    if search != ""
      Problem.where('title LIKE(?)', "%#{search}%")
    else
      Problem.all
    end
  end


  with_options presence: true do
    validates :title, length: { maximum: 20}
    validates :text, length: { minimum: 15, maximum: 200 }
    validates :genre
  end
    validates :genre_id, numericality: { other_than: 1, message:  "を選んで下さい"} 
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/solved_worrie.rb
class SolvedWorrie < ApplicationRecord
  belongs_to :problem
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend ActiveHash::Associations::ActiveRecordExtensions
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  has_many :problems
  has_many :comments
  has_many :sns_credentials
  has_many :best_users
  belongs_to_active_hash :gender

  validates :name, presence: true
  validates :self_introduction, length: { maximum: 160 }
  validates :password ,format:  { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,100}+\z/i, message: "は半角英数字混合で入力してください"}, on: :create


  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :self_introduction, :gender_id, :birthday])
  end
end

app/controllers/best_users_controller.rb
class BestUsersController < ApplicationController

  def best_create
    if BestUser.create(user_id: params[:user_id],problem_id: params[:id])
      redirect_to problem_path(params[:id])
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  
    @comment = Comment.new(comment_params)
    
    if @comment.save
      ActionCable.server.broadcast 'message_channel', content: @comment
      
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment_text).merge(user_id: current_user.id, problem_id: params[:problem_id])
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:search]


  def index
    @problems = Problem.includes(:user).order("created_at DESC")
  end

  def new
    @problem = Problem.new
  end

  def create
    @problem = Problem.new(problem_params)
    if @problem.save
      redirect_to problem_path(@problem.id)
    else
      render :new
    end
  end

  def show
    @problem = Problem.find(params[:id])
    @comment = Comment.new
    @comments = @problem.comments.includes(:problem,:user).order("created_at ASC")
  end
  
  def search
   
    @problems = Problem.search(params[:keyword])
  end

  def edit
    @problem = Problem.find(params[:id])
  end

  def update
    @problem = Problem.find(params[:id])
    if @problem.update(problem_params)
      redirect_to problem_path(@problem.id)
    else
      render :edit
    end
  end

  def destroy
    @problem =Problem.find(params[:id])
    if @problem.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def best_answer
    @comments = Comment.select(:problem_id, :user_id).distinct.where(problem_id: params[:id]).where.not(user_id: current_user.id)
    @problem = Problem.find(params[:id])
  end

  private

  def problem_params
    params.require(:problem).permit(:image,:title, :text, :genre_id).merge(user_id: current_user.id)
  end
end

app/controllers/solved_worries_controller.rb
class SolvedWorriesController < ApplicationController

  def create
    problem = Problem.find(params[:problem_id])
    if solved_worrie = SolvedWorrie.create(problem_id: problem.id)
      redirect_to problem_path(problem.id)
    end
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
    @user = User.find(params[:id])
  end

  def profile_edit
    @user = User.find(params[:id])
  end

  def profile_update
    @user = User.find(params[:id])
    if @user.update(profile_params)
      redirect_to profile_user_path(@user.id)
    else
      render :edit
    end
  end

  def show
  @user = User.find(params[:id])
  @name = @user.name
  @problems = @user.problems
  end

  def profile_params
    params.require(:user).permit(:name,:self_introduction, :gender_id, :birthday)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/best_users_helper.rb
module BestUsersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/solved_worries_helper.rb
module SolvedWorriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/problems/_header.html.erb
<header class='top-page-header'>    
  <%= link_to root_path,class: 'title-link', method: :get do%>
    <h1>Solved</h1>
  <%end%>
    <%= form_with url: search_problems_path, class:"search-form",method: :get, local: true do |f| %>
      <%= f.text_field :keyword,  placeholder:'キーワードから探す' , class:'input-box'%>
      <%= f.submit "検索",class: "search-button" %>
    <%end%>
    <div class='nav'>
      <ul class='lists'>      
        <% if user_signed_in? %>
          <li><%= link_to current_user.name, profile_user_path(current_user.id), class: "user-name" %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
        <% else %>
          <%= link_to 'ログイン', user_session_path, class: "login" %>          
        <% end %>      
      </ul>
    </div>
  </header>

app/views/problems/_header2.html.erb
<header class='top-page-header-2'>    
  <%= link_to root_path,class: 'title-link', method: :get do%>
    <h1>Solved</h1>
  <%end%>    
</header>

app/views/problems/best_answer.html.erb
<%= render partial: "problems/header2" %>

<div class='form-header'>
  <h1 class='form-header-text'>
    回答をしてくれたユーザー
  </h1>
</div>

<div class="texts-header-short">
  <p>一番良いコメントをしてくれたユーザーを選択してください</p>
</div>

<div class="good-comment-users">
  <% @comments.each do |comment|%>
  <div class="good-comment-user">
    <%= link_to  "/user/#{comment.user.id}/problem/#{@problem.id}",class: "best-answer-users-link", method: :post do %>
      <%= "#{comment.user.name}さん" %>
    <%end%>
  </div>
  <%end%>
</div>

app/views/problems/edit.html.erb
<%= render partial: "problems/header" %>

<%= form_with model: @problem, url: problem_path , class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      相談内容
    </h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>
  
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">タイトル</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :title, class:"input-default", id:"user-name", placeholder:"タイトルを入力してください", maxlength:"40" %>
  </div>
  
  <div class="form-group-text">
    <div class='form-text-wrap'>
      <label class="form-text">内容</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :text, class:"input-name", id:"first-name", placeholder:"相談内容を入力してください。" %>
    </div>
  </div>
    <div class="img-upload">
      <div class="click-upload">
        <p>
          クリックして画像を添付
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>

    <div id="image-list" class="image-preview"></div>

  <div class="form-group-text-genre">
    <div class='form-text-wrap'>
      <label class="form-text">ジャンル</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='form-jender'>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"jender", id:""})%>
    </div>
  </div>
  
  
  <div class='register-btn'>
    <%= f.submit "更新する" ,class:"register-red-btn" %>
  </div>
</div>
<% end %>

app/views/problems/index.html.erb
<%= render partial: "problems/header" %>

<div class='problems'>
  <% @problems.each do |problem| %>
    <div class='problem-lists'>
      <%= link_to problem_path(problem.id),class:"link-title", method: :get do %>
        <div class="problem-text">
          <p class="problem"><%= problem.title %></p>
        </div>
      <% end %>
      <% if problem.solved_worrie != nil%>
        <div class="problem-solved">
          <h4>解決済み</h4>
        </div>
      <%end%>
    </div>
  <% end %>
</div>

<div class='purchase-btn'>
  <a class='purchase-btn-text' href="/problems/new"><span class=problem-mark>Q</span>お悩み相談する</a>
</div>

app/views/problems/new.html.erb
<%= render partial: "problems/header" %>

<%= form_with model: @problem, url: problems_path , class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      相談内容
    </h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>
  
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">タイトル</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :title, class:"input-default", id:"user-name", placeholder:"タイトルを入力してください", maxlength:"40" %>
  </div>
  
  <div class="form-group-text">
    <div class='form-text-wrap'>
      <label class="form-text">内容</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :text, class:"input-name", id:"first-name", placeholder:"相談内容を入力してください。" %>
    </div>
  </div>

    <div class="img-upload">
      <div class="click-upload">
        <p>
          クリックして画像を添付
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>

    <div id="image-list" class="image-preview"></div>


  <div class="form-group-text-genre">
    <div class='form-text-wrap'>
      <label class="form-text">ジャンル</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='form-jender'>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"jender", id:""})%>
    </div>
  </div>
  
  
  <div class='register-btn'>
    <%= f.submit "投稿する" ,class:"register-red-btn" %>
  </div>
</div>
<% end %>

app/views/problems/search.html.erb
<%= render partial: "problems/header" %>

<div class='problems'>
  <% @problems.each do |problem| %>
    <div class='problem-lists'>
      <%= link_to problem_path(problem.id),class:"link-title", method: :get do %>
        <div class="problem-text">
          <p class="problem"><%= problem.title %></p>
        </div>
      <% end %>
      <% if problem.solved_worrie != nil%>
        <div class="problem-solved">
          <h4>解決済み</h4>
        </div>
      <%end%>
    </div>
  <% end %>
</div>

<div class='purchase-btn'>
  <a class='purchase-btn-text' href="/problems/new"><span class=problem-mark>Q</span>お悩み相談する</a>
</div>

app/views/problems/show.html.erb
<%= render partial: "problems/header" %>

<div class='form-header'>
  <h1 class='form-header-text'>
    <%= link_to profile_user_path(@problem.user.id), class:"user-name-link",method: :get do%>
    <%= "#{@problem.user.name}さんの投稿" %>
    <%end%>
  </h1>
</div>

<div class="details">
  <div class="detail-title">
    <p class="created-at"><%= @problem.created_at.strftime("%Y-%m-%d %H:%M") %></p>
    <h2><%= @problem.title %></h2>
  </div>
  <div class="detail-text">
    <p><%= @problem.text %></p>
  </div>
  <%= image_tag @problem.image.variant(resize: '150x300'), class: 'message-image' if @problem.image.attached? %>
  <div class="genre-selected">
    <%="カテゴリー：#{@problem.genre.name}"%>
  </div>
</div>

<div class="show-config">
  <% if user_signed_in? && (current_user.id == @problem.user_id) && @problem.solved_worrie == nil %>
    <div class="edit-problem">
      <%= link_to "投稿を編集する" ,edit_problem_path(@problem.id) ,class:"edit-btn"%>
    </div>
    <div class="destroy-problem">
      <%= link_to "投稿を削除する" , problem_path(@problem.id) ,class:"destroy-btn", method: :delete%>
    </div> 
    <% if current_user && @problem.solved_worrie == nil%>
    <div>
    <%= link_to "問題が解決した" ,  problem_solved_worries_path(@problem.id),class:"solved-btn-pink", method: :post%>
    </div>
    <% end %>
  <% elsif user_signed_in? && current_user.id == @problem.user_id %>   
    <div class="destroy-problem">
      <%= link_to "投稿を削除する" ,problem_path(@problem.id) ,class:"destroy-btn", method: :delete%>
    </div> 
  <% end %>
</div>

<div class="solved-text">
  <% if current_user && @problem.solved_worrie != nil %>
    <h2>この悩みは解決しました</h2>
  <%end%>
</div>

<div class="best-answer-select">
  <% if (@problem.best_user == nil && @problem.solved_worrie != nil) && user_signed_in? && (current_user.id == @problem.user_id)%>
  <div>
    <%= link_to "ベストアンサーを選択する", best_answer_problem_path(@problem.id),class: "best-answer-select-link", method: :get%>
  </div>
  <%elsif @problem.best_user != nil && @problem.solved_worrie != nil%>
  <div class="best-answer-name">
    <%= link_to profile_user_path(@problem.best_user.user.id),class: "best-answer-name-link" ,method: :get do %>
      <%= "ベストアンサーは#{@problem.best_user.user.name}さんです" %>
    <%end%>
  </div>
  <%end%>
</div>

<div class="comments-lists-block">
  <div class="container">
    <% if current_user && @problem.solved_worrie == nil%>
      <%= form_with(model: [@problem, @comment]) do |form| %>
        <%= form.text_area :comment_text, placeholder: "コメントする",class:"comments-box", rows: "2" %><br>
        <%= form.submit "コメントを送信する"  ,class:"comment-submit"%>
      <% end %>
    <% elsif current_user && @problem.solved_worrie != nil%>  
        <strong><p class="solved-comment-no">※※※ 既に解決済みのためコメントはできません ※※※</p></strong>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
  </div>
  <h4 class="comment-lists-title">コメント一覧</h4>
  <div class="comment-list" id='comment-list'>
    <% @comments.each do |comment| %>
    <div class="comment-text-lists">
      <div class="comment-user-config">
        <%=link_to "#{comment.user.name}さん" ,profile_user_path(comment.user.id),class:"comment-user-name-link",method: :get%>        
      </div>
      <div class="comment-textes">
        <p><%= comment.comment_text %></p>
        <p class="created-times"><%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></p>
      </div>
    </div>
    <%end%>
  </div>
</div>