config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "problems#index"
  resources :users, only: [:show] do
    member do
      get 'profile'
      patch 'profile_update'
      get 'profile_edit'
    end
  end

  resources :problems do
    resources :comments, only: :create
    resources :solved_worries, only: :create
    collection do
      get 'search'
    end
    member do
      get 'best_answer'
    end
  end

  
    
  

  post 'user/:user_id/problem/:id', to: 'best_users#best_create'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend ActiveHash::Associations::ActiveRecordExtensions
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  has_many :problems
  has_many :comments
  has_many :sns_credentials
  has_many :best_users
  belongs_to_active_hash :gender

  validates :name, presence: true
  validates :self_introduction, length: { maximum: 160 }
  validates :password ,format:  { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,100}+\z/i, message: "は半角英数字混合で入力してください"}, on: :create


  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
    @user = User.find(params[:id])
  end

  def profile_edit
    @user = User.find(params[:id])
  end

  def profile_update
    @user = User.find(params[:id])
    if @user.update(profile_params)
      redirect_to profile_user_path(@user.id)
    else
      render :edit
    end
  end

  def show
  @user = User.find(params[:id])
  @name = @user.name
  @problems = @user.problems
  end

  def profile_params
    params.require(:user).permit(:name,:self_introduction, :gender_id, :birthday)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/profile.html.erb
<%= render partial: "problems/header2" %>

<div class='form-header'>
    <h1 class='form-header-text-profile'>
     <%= "#{@user.name}さんのプロフィール"%> 
    </h1>
</div>
 
 <h4 class="self-introduction-title">自己紹介</h4>
<div class="profiles">
  <div class="profile-text">
    <p><%= @user.self_introduction %></p>
  </div>
  <div class="profile-jender">
    <h4 class="blue-title">性別</h4>
    <p><%= @user.gender.name %></p>
  </div>
  <div class="profile-birthday">
    <h4 class="blue-title">生年月日</h4>
    <% if @user.birthday != nil %>
    <pre><%= "#{@user.birthday.year}年 #{@user.birthday.month}月 #{@user.birthday.day}日" %></pre>
    <%else%>
    <p>非公開</p>
    <%end%>
  </div>

  <div class="best-answer-length">
    <h4 class="blue-title">ベストアンサーに選ばれた回数</h4>
    <p><%="#{@user.best_users.length}回" %></p>
  </div>
</div>

<div class="profile-settings">
  <div class="user-previews-links">
    <div class="user-previews-link">
      <%= link_to user_path(@user.id) ,class:"user-previews-link-go", method: :get do%>
        <h2><%="#{@user.name}さんの投稿一覧"%></h2>
      <%end%>
    </div>
  </div>
  <div class="edits">
    <% if user_signed_in? && current_user.id == @user.id%>
      <div class="profile-edit">
      <%= link_to profile_edit_user_path(@user.id),class:"profile-edit-user-link", method: :get do %>
        <h2>プロフィールを編集</h2>
      <%end%>
      </div>
    <%end%>
  </div>
</div>

app/views/users/profile_edit.html.erb
<%= render partial: "problems/header2" %>

<%= form_with model: @user, url: profile_update_user_path(@user.id) ,method: :patch, class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      プロフィール編集
    </h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>


  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ユーザーネーム</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :name, class:"input-default", id:"user-name", placeholder:"お好きな名前を入力してください", maxlength:"40" %>
  </div>
  
  
  <div class="form-group">
    <p class='form-info-header'>
      自己紹介
    </p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">自己紹介文</label>
      <span class="indispensable">任意</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :self_introduction, class:"input-name", id:"first-name", placeholder:"自己紹介文を入力してください" %>
      
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">性別</label>
      <span class="indispensable">任意</span>
    </div>
    <div class='form-jender'>
      <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"jender", id:""})%>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">任意</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
  </div>
  
  <div class='register-btn'>
    <%= f.submit "更新" ,class:"register-red-btn" %>
  </div>
</div>
<% end %>

app/views/users/show.html.erb
<%= render partial: "problems/header2" %>

<div class='form-header'>
  <h1 class='form-header-text'>
    <%= link_to profile_user_path(@user.id), class:"user-name-link",method: :get do%>
    <%= @user.name %>
    <%end%>
    <span>さんの投稿一覧</span>
  </h1>
</div>


<div class='problems'>
  <% @problems.each do |problem| %> 
    <div class='problem-lists'>
      <%= link_to problem_path(problem.id),class:"link-title", method: :get do %>
        <div class="problem-text">
          <p class="problem"><%= problem.title %></p>
        </div>
      <% end %>
      <% if problem.solved_worrie != nil%>
        <div class="problem-solved">
          <h4>解決済み</h4>
        </div>
      <%end%>
    </div>
  <% end %>
</div>

<div class='purchase-btn'>
  <a class='purchase-btn-text' href="/problems/new"><span class=problem-mark>Q</span>お悩み相談する</a>
</div>